services:
  db:
    image: postgres:16.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: er_project_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: ./bin/rails server -b 0.0.0.0
    volumes:
      - .:/rails
      - ./storage:/rails/storage
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@db/er_project_development
    depends_on:
      - db

volumes:
  postgres-data:
  bundle_cache:
