# Database Configuration
# This application is configured with default database settings for ease of use.
# To configure this application for production:
#  - Update this database.yml with secure credentials.
#  - You should use environment variables for proper security control.
# t. PM

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'postgres' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'password' } %>
  # Change the host to localhost for local development
  # host: localhost
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: er_project_development

test:
  <<: *default
  database: er_project_test

production:
  <<: *default
  database: er_project_production


